# Generated by Django 2.1.1 on 2018-09-02 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('date', models.DateTimeField(null=True)),
                ('priority', models.CharField(choices=[('important', 'important'), ('hot', 'hot')], max_length=128)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.Categories', verbose_name='categorie')),
            ],
        ),
        migrations.RemoveField(
            model_name='tmuser',
            name='group',
        ),
        migrations.DeleteModel(
            name='TmGroup',
        ),
        migrations.DeleteModel(
            name='TmUser',
        ),
    ]
