# Generated by Django 2.1.1 on 2018-09-14 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MyApp', '0003_auto_20180902_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=2048)),
                ('fromwho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromwho', to=settings.AUTH_USER_MODEL)),
                ('towho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='towho', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='create_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
