# Generated by Django 2.1.1 on 2018-09-14 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_auto_20180914_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('medium', 'medium'), ('high', 'high'), ('very high', 'very high')], max_length=128, null=True),
        ),
    ]
